// <auto-generated />
using System;
using FootballManager.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FootballManager.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FootballManagerDbContext))]
    [Migration("20260926025940_AllowFixtureReplay")]
    partial class AllowFixtureReplay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FootballManager.Domain.Common.Name", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("value")
                        .HasJsonPropertyName("value");

                    b.HasKey("Id")
                        .HasName("pk_names");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_names_value");

                    b.ToTable("names", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Common.Surname", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("value")
                        .HasJsonPropertyName("value");

                    b.HasKey("Id")
                        .HasName("pk_surnames");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_surnames_value");

                    b.ToTable("surnames", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Competitions.CompetitionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_season_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_competition_participants");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_competition_participants_team_id");

                    b.HasIndex("CompetitionSeasonId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_participants_competition_season_id_team_id");

                    b.ToTable("competition_participants", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Competitions.CompetitionSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.HasKey("Id")
                        .HasName("pk_competition_seasons");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_competition_seasons_season_id");

                    b.HasIndex("CompetitionId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_seasons_competition_id_season_id");

                    b.ToTable("competition_seasons", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Competitions.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_season_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.HasKey("Id")
                        .HasName("pk_rounds");

                    b.HasIndex("CompetitionSeasonId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_rounds_competition_season_id_number");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Matches.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_fixtures");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_fixtures_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_fixtures_home_team_id");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_fixtures_round_id");

                    b.ToTable("fixtures", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentMinute")
                        .HasColumnType("integer")
                        .HasColumnName("current_minute");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("fixture_id");

                    b.Property<string>("Half")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("half");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<int>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_matches_away_team_id");

                    b.HasIndex("FixtureId")
                        .HasDatabaseName("ix_matches_fixture_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_matches_home_team_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_matches_status");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Matches.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("SecondaryPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_player_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_match_events");

                    b.HasIndex("MatchId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_match_events_match_id_sequence");

                    b.ToTable("match_events", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Matches.MatchStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayCorners")
                        .HasColumnType("integer")
                        .HasColumnName("away_corners");

                    b.Property<int>("AwayFouls")
                        .HasColumnType("integer")
                        .HasColumnName("away_fouls");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<int>("AwayPossession")
                        .HasColumnType("integer")
                        .HasColumnName("away_possession");

                    b.Property<int>("AwayRedCards")
                        .HasColumnType("integer")
                        .HasColumnName("away_red_cards");

                    b.Property<int>("AwaySaves")
                        .HasColumnType("integer")
                        .HasColumnName("away_saves");

                    b.Property<int>("AwayShots")
                        .HasColumnType("integer")
                        .HasColumnName("away_shots");

                    b.Property<int>("AwayShotsOnTarget")
                        .HasColumnType("integer")
                        .HasColumnName("away_shots_on_target");

                    b.Property<int>("AwaySubstitutions")
                        .HasColumnType("integer")
                        .HasColumnName("away_substitutions");

                    b.Property<int>("AwayYellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("away_yellow_cards");

                    b.Property<int>("HomeCorners")
                        .HasColumnType("integer")
                        .HasColumnName("home_corners");

                    b.Property<int>("HomeFouls")
                        .HasColumnType("integer")
                        .HasColumnName("home_fouls");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<int>("HomePossession")
                        .HasColumnType("integer")
                        .HasColumnName("home_possession");

                    b.Property<int>("HomeRedCards")
                        .HasColumnType("integer")
                        .HasColumnName("home_red_cards");

                    b.Property<int>("HomeSaves")
                        .HasColumnType("integer")
                        .HasColumnName("home_saves");

                    b.Property<int>("HomeShots")
                        .HasColumnType("integer")
                        .HasColumnName("home_shots");

                    b.Property<int>("HomeShotsOnTarget")
                        .HasColumnType("integer")
                        .HasColumnName("home_shots_on_target");

                    b.Property<int>("HomeSubstitutions")
                        .HasColumnType("integer")
                        .HasColumnName("home_substitutions");

                    b.Property<int>("HomeYellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("home_yellow_cards");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.HasKey("Id")
                        .HasName("pk_match_statistics");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_statistics_match_id");

                    b.ToTable("match_statistics", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Accuracy")
                        .HasColumnType("integer")
                        .HasColumnName("accuracy");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<int>("Dribbling")
                        .HasColumnType("integer")
                        .HasColumnName("dribbling");

                    b.Property<int>("GoalkeeperPower")
                        .HasColumnType("integer")
                        .HasColumnName("goalkeeper_power");

                    b.Property<int>("Heading")
                        .HasColumnType("integer")
                        .HasColumnName("heading");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("position");

                    b.Property<int>("Reflexes")
                        .HasColumnType("integer")
                        .HasColumnName("reflexes");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_players_name");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Players.PlayerSeasonState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<string>("Injury")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("injury");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer")
                        .HasColumnName("red_cards");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<int>("SuspensionMatches")
                        .HasColumnType("integer")
                        .HasColumnName("suspension_matches");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("yellow_cards");

                    b.HasKey("Id")
                        .HasName("pk_player_season_states");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_player_season_states_team_id");

                    b.HasIndex("PlayerId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_season_states_player_id_season_id");

                    b.HasIndex("SeasonId", "TeamId")
                        .HasDatabaseName("ix_player_season_states_season_id_team_id");

                    b.ToTable("player_season_states", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Seasons.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_name");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("primary_color");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("secondary_color");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("short_name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Teams.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_team_memberships");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_team_memberships_player_id");

                    b.HasIndex("TeamId", "StartDate")
                        .HasDatabaseName("ix_team_memberships_team_id_start_date");

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("FootballManager.Domain.Competitions.CompetitionParticipant", b =>
                {
                    b.HasOne("FootballManager.Domain.Competitions.CompetitionSeason", null)
                        .WithMany()
                        .HasForeignKey("CompetitionSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_participants_competition_seasons_competition_se");

                    b.HasOne("FootballManager.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_participants_teams_team_id");
                });

            modelBuilder.Entity("FootballManager.Domain.Competitions.CompetitionSeason", b =>
                {
                    b.HasOne("FootballManager.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_seasons_competitions_competition_id");

                    b.HasOne("FootballManager.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_seasons_seasons_season_id");
                });

            modelBuilder.Entity("FootballManager.Domain.Competitions.Round", b =>
                {
                    b.HasOne("FootballManager.Domain.Competitions.CompetitionSeason", null)
                        .WithMany()
                        .HasForeignKey("CompetitionSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_competition_seasons_competition_season_id");
                });

            modelBuilder.Entity("FootballManager.Domain.Matches.Fixture", b =>
                {
                    b.HasOne("FootballManager.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_teams_away_team_id");

                    b.HasOne("FootballManager.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_teams_home_team_id");

                    b.HasOne("FootballManager.Domain.Competitions.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_rounds_round_id");
                });

            modelBuilder.Entity("FootballManager.Domain.Matches.Match", b =>
                {
                    b.HasOne("FootballManager.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_teams_away_team_id");

                    b.HasOne("FootballManager.Domain.Matches.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_fixtures_fixture_id");

                    b.HasOne("FootballManager.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_teams_home_team_id");
                });

            modelBuilder.Entity("FootballManager.Domain.Matches.MatchEvent", b =>
                {
                    b.HasOne("FootballManager.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_events_matches_match_id");
                });

            modelBuilder.Entity("FootballManager.Domain.Matches.MatchStatistics", b =>
                {
                    b.HasOne("FootballManager.Domain.Matches.Match", null)
                        .WithOne()
                        .HasForeignKey("FootballManager.Domain.Matches.MatchStatistics", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_statistics_matches_match_id");
                });

            modelBuilder.Entity("FootballManager.Domain.Players.PlayerSeasonState", b =>
                {
                    b.HasOne("FootballManager.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_states_players_player_id");

                    b.HasOne("FootballManager.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_states_seasons_season_id");

                    b.HasOne("FootballManager.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_states_teams_team_id");
                });

            modelBuilder.Entity("FootballManager.Domain.Teams.TeamMembership", b =>
                {
                    b.HasOne("FootballManager.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_players_player_id");

                    b.HasOne("FootballManager.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_teams_team_id");
                });
#pragma warning restore 612, 618
        }
    }
}
