// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NinjaEleven.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NinjaEleven.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NinjaElevenDbContext))]
    [Migration("20260928213012_PlayerAge")]
    partial class PlayerAge
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NinjaEleven.Domain.Common.Name", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("value")
                        .HasJsonPropertyName("value");

                    b.HasKey("Id")
                        .HasName("pk_names");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_names_value");

                    b.ToTable("names", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Common.Surname", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("value")
                        .HasJsonPropertyName("value");

                    b.HasKey("Id")
                        .HasName("pk_surnames");

                    b.HasIndex("Value")
                        .IsUnique()
                        .HasDatabaseName("ix_surnames_value");

                    b.ToTable("surnames", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.Competition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_competitions");

                    b.ToTable("competitions", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.CompetitionParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_season_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_competition_participants");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_competition_participants_team_id");

                    b.HasIndex("CompetitionSeasonId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_participants_competition_season_id_team_id");

                    b.ToTable("competition_participants", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.CompetitionSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_id");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("division_id");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.HasKey("Id")
                        .HasName("pk_competition_seasons");

                    b.HasIndex("DivisionId")
                        .HasDatabaseName("ix_competition_seasons_division_id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_competition_seasons_season_id");

                    b.HasIndex("CompetitionId", "SeasonId", "DivisionId")
                        .IsUnique()
                        .HasDatabaseName("ix_competition_seasons_competition_id_season_id_division_id");

                    b.ToTable("competition_seasons", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.CupTie", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("AggregateAwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_away_goals");

                    b.Property<int?>("AggregateHomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("aggregate_home_goals");

                    b.Property<int?>("AwayPenaltyGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_penalty_goals");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<Guid>("CompetitionSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_season_id");

                    b.Property<Guid?>("FirstLegFixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("first_leg_fixture_id");

                    b.Property<int?>("HomePenaltyGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_penalty_goals");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<Guid?>("LoserTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("loser_team_id");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("round_number");

                    b.Property<Guid?>("SecondLegFixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("second_leg_fixture_id");

                    b.Property<Guid?>("WinnerTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_team_id");

                    b.HasKey("Id")
                        .HasName("pk_cup_ties");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_cup_ties_away_team_id");

                    b.HasIndex("FirstLegFixtureId")
                        .HasDatabaseName("ix_cup_ties_first_leg_fixture_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_cup_ties_home_team_id");

                    b.HasIndex("LoserTeamId")
                        .HasDatabaseName("ix_cup_ties_loser_team_id");

                    b.HasIndex("SecondLegFixtureId")
                        .HasDatabaseName("ix_cup_ties_second_leg_fixture_id");

                    b.HasIndex("WinnerTeamId")
                        .HasDatabaseName("ix_cup_ties_winner_team_id");

                    b.HasIndex("CompetitionSeasonId", "RoundNumber")
                        .HasDatabaseName("ix_cup_ties_competition_season_id_round_number");

                    b.ToTable("cup_ties", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.MatchDay", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.HasKey("Id")
                        .HasName("pk_match_days");

                    b.HasIndex("SeasonId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_match_days_season_id_number");

                    b.ToTable("match_days", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.Round", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_season_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("MatchDayId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_day_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<int>("Window")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("window");

                    b.HasKey("Id")
                        .HasName("pk_rounds");

                    b.HasIndex("MatchDayId")
                        .HasDatabaseName("ix_rounds_match_day_id");

                    b.HasIndex("CompetitionSeasonId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_rounds_competition_season_id_number");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.TrophyAward", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CompetitionSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("competition_season_id");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid")
                        .HasColumnName("division_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<decimal>("PrizeMoney")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("prize_money");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<DateTimeOffset>("WonAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("won_at");

                    b.HasKey("Id")
                        .HasName("pk_trophy_awards");

                    b.HasIndex("CompetitionSeasonId")
                        .HasDatabaseName("ix_trophy_awards_competition_season_id");

                    b.HasIndex("DivisionId")
                        .HasDatabaseName("ix_trophy_awards_division_id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_trophy_awards_season_id");

                    b.HasIndex("TeamId", "SeasonId")
                        .HasDatabaseName("ix_trophy_awards_team_id_season_id");

                    b.ToTable("trophy_awards", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Finance.FinanceMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("amount");

                    b.Property<decimal>("BalanceAfter")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("balance_after");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<int?>("MatchDayNumber")
                        .HasColumnType("integer")
                        .HasColumnName("match_day_number");

                    b.Property<Guid?>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Reference")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("reference");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_finance_movements");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("ix_finance_movements_match_id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("ix_finance_movements_season_id");

                    b.HasIndex("TeamId", "Sequence")
                        .HasDatabaseName("ix_finance_movements_team_id_sequence");

                    b.HasIndex("TeamId", "SeasonId", "Sequence")
                        .HasDatabaseName("ix_finance_movements_team_id_season_id_sequence");

                    b.ToTable("finance_movements", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Managers.Manager", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_managers");

                    b.HasIndex("TeamId")
                        .IsUnique()
                        .HasDatabaseName("ix_managers_team_id");

                    b.ToTable("managers", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("round_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_fixtures");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_fixtures_away_team_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_fixtures_home_team_id");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_fixtures_round_id");

                    b.ToTable("fixtures", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attendance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attendance");

                    b.Property<decimal>("AwayRevenue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("away_revenue");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("away_team_id");

                    b.Property<string>("CompetitionType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("competition_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentMinute")
                        .HasColumnType("integer")
                        .HasColumnName("current_minute");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("fixture_id");

                    b.Property<decimal>("GrossRevenue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("gross_revenue");

                    b.Property<string>("Half")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("half");

                    b.Property<decimal>("HomeRevenue")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("home_revenue");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("home_team_id");

                    b.Property<int>("Seed")
                        .HasColumnType("integer")
                        .HasColumnName("seed");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<decimal>("TicketPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("ticket_price");

                    b.Property<int>("Window")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("window");

                    b.HasKey("Id")
                        .HasName("pk_matches");

                    b.HasIndex("AwayTeamId")
                        .HasDatabaseName("ix_matches_away_team_id");

                    b.HasIndex("FixtureId")
                        .HasDatabaseName("ix_matches_fixture_id");

                    b.HasIndex("HomeTeamId")
                        .HasDatabaseName("ix_matches_home_team_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_matches_status");

                    b.ToTable("matches", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.MatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer")
                        .HasColumnName("away_score");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer")
                        .HasColumnName("home_score");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Minute")
                        .HasColumnType("integer")
                        .HasColumnName("minute");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid?>("SecondaryPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("secondary_player_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_match_events");

                    b.HasIndex("MatchId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_match_events_match_id_sequence");

                    b.ToTable("match_events", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.MatchPlayerStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Assists")
                        .HasColumnType("integer")
                        .HasColumnName("assists");

                    b.Property<bool>("CameOn")
                        .HasColumnType("boolean")
                        .HasColumnName("came_on");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<bool>("InjuredOff")
                        .HasColumnType("boolean")
                        .HasColumnName("injured_off");

                    b.Property<int>("InjuryMatchesOut")
                        .HasColumnType("integer")
                        .HasColumnName("injury_matches_out");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("OwnGoals")
                        .HasColumnType("integer")
                        .HasColumnName("own_goals");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer")
                        .HasColumnName("red_cards");

                    b.Property<int>("Saves")
                        .HasColumnType("integer")
                        .HasColumnName("saves");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<bool>("Started")
                        .HasColumnType("boolean")
                        .HasColumnName("started");

                    b.Property<bool>("SubbedOff")
                        .HasColumnType("boolean")
                        .HasColumnName("subbed_off");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<bool>("WasInjured")
                        .HasColumnType("boolean")
                        .HasColumnName("was_injured");

                    b.Property<bool>("WasOnBenchUnused")
                        .HasColumnType("boolean")
                        .HasColumnName("was_on_bench_unused");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("yellow_cards");

                    b.HasKey("Id")
                        .HasName("pk_match_player_statistics");

                    b.HasIndex("MatchId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_player_statistics_match_id_player_id");

                    b.HasIndex("PlayerId", "SeasonId")
                        .HasDatabaseName("ix_match_player_statistics_player_id_season_id");

                    b.ToTable("match_player_statistics", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.MatchStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AwayCorners")
                        .HasColumnType("integer")
                        .HasColumnName("away_corners");

                    b.Property<string>("AwayFormation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("away_formation");

                    b.Property<int>("AwayFouls")
                        .HasColumnType("integer")
                        .HasColumnName("away_fouls");

                    b.Property<int>("AwayGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_goals");

                    b.Property<int>("AwayInjuries")
                        .HasColumnType("integer")
                        .HasColumnName("away_injuries");

                    b.Property<int>("AwayOwnGoals")
                        .HasColumnType("integer")
                        .HasColumnName("away_own_goals");

                    b.Property<int>("AwayPossession")
                        .HasColumnType("integer")
                        .HasColumnName("away_possession");

                    b.Property<int>("AwayRedCards")
                        .HasColumnType("integer")
                        .HasColumnName("away_red_cards");

                    b.Property<int>("AwaySaves")
                        .HasColumnType("integer")
                        .HasColumnName("away_saves");

                    b.Property<int>("AwayShots")
                        .HasColumnType("integer")
                        .HasColumnName("away_shots");

                    b.Property<int>("AwayShotsOnTarget")
                        .HasColumnType("integer")
                        .HasColumnName("away_shots_on_target");

                    b.Property<int>("AwaySubstitutions")
                        .HasColumnType("integer")
                        .HasColumnName("away_substitutions");

                    b.Property<int>("AwayYellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("away_yellow_cards");

                    b.Property<int>("HomeCorners")
                        .HasColumnType("integer")
                        .HasColumnName("home_corners");

                    b.Property<string>("HomeFormation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_formation");

                    b.Property<int>("HomeFouls")
                        .HasColumnType("integer")
                        .HasColumnName("home_fouls");

                    b.Property<int>("HomeGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_goals");

                    b.Property<int>("HomeInjuries")
                        .HasColumnType("integer")
                        .HasColumnName("home_injuries");

                    b.Property<int>("HomeOwnGoals")
                        .HasColumnType("integer")
                        .HasColumnName("home_own_goals");

                    b.Property<int>("HomePossession")
                        .HasColumnType("integer")
                        .HasColumnName("home_possession");

                    b.Property<int>("HomeRedCards")
                        .HasColumnType("integer")
                        .HasColumnName("home_red_cards");

                    b.Property<int>("HomeSaves")
                        .HasColumnType("integer")
                        .HasColumnName("home_saves");

                    b.Property<int>("HomeShots")
                        .HasColumnType("integer")
                        .HasColumnName("home_shots");

                    b.Property<int>("HomeShotsOnTarget")
                        .HasColumnType("integer")
                        .HasColumnName("home_shots_on_target");

                    b.Property<int>("HomeSubstitutions")
                        .HasColumnType("integer")
                        .HasColumnName("home_substitutions");

                    b.Property<int>("HomeYellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("home_yellow_cards");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.HasKey("Id")
                        .HasName("pk_match_statistics");

                    b.HasIndex("MatchId")
                        .IsUnique()
                        .HasDatabaseName("ix_match_statistics_match_id");

                    b.ToTable("match_statistics", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Accuracy")
                        .HasColumnType("integer")
                        .HasColumnName("accuracy");

                    b.Property<int>("Age")
                        .HasColumnType("integer")
                        .HasColumnName("age");

                    b.Property<int>("Dribbling")
                        .HasColumnType("integer")
                        .HasColumnName("dribbling");

                    b.Property<string>("Face")
                        .HasColumnType("jsonb")
                        .HasColumnName("face");

                    b.Property<int>("GoalkeeperPower")
                        .HasColumnType("integer")
                        .HasColumnName("goalkeeper_power");

                    b.Property<int>("Heading")
                        .HasColumnType("integer")
                        .HasColumnName("heading");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("position");

                    b.Property<int>("Reflexes")
                        .HasColumnType("integer")
                        .HasColumnName("reflexes");

                    b.Property<int>("Speed")
                        .HasColumnType("integer")
                        .HasColumnName("speed");

                    b.Property<int>("Strength")
                        .HasColumnType("integer")
                        .HasColumnName("strength");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_players_name");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Players.PlayerSeasonState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Energy")
                        .HasColumnType("integer")
                        .HasColumnName("energy");

                    b.Property<int>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int>("Injuries")
                        .HasColumnType("integer")
                        .HasColumnName("injuries");

                    b.Property<string>("Injury")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("injury");

                    b.Property<int>("InjuryMatchesRemaining")
                        .HasColumnType("integer")
                        .HasColumnName("injury_matches_remaining");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer")
                        .HasColumnName("red_cards");

                    b.Property<bool>("Retiring")
                        .HasColumnType("boolean")
                        .HasColumnName("retiring");

                    b.Property<int>("Saves")
                        .HasColumnType("integer")
                        .HasColumnName("saves");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<int>("SuspensionMatches")
                        .HasColumnType("integer")
                        .HasColumnName("suspension_matches");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer")
                        .HasColumnName("yellow_cards");

                    b.HasKey("Id")
                        .HasName("pk_player_season_states");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_player_season_states_team_id");

                    b.HasIndex("PlayerId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_season_states_player_id_season_id");

                    b.HasIndex("SeasonId", "TeamId")
                        .HasDatabaseName("ix_player_season_states_season_id_team_id");

                    b.ToTable("player_season_states", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Seasons.Division", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.HasKey("Id")
                        .HasName("pk_divisions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_divisions_name");

                    b.HasIndex("Tier")
                        .IsUnique()
                        .HasDatabaseName("ix_divisions_tier");

                    b.ToTable("divisions", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Seasons.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_seasons");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_name");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_seasons_number");

                    b.ToTable("seasons", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Sponsors.Sponsor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("color");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("industry");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sponsors");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_sponsors_name");

                    b.ToTable("sponsors", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Sponsors.SponsorContract", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContractMatches")
                        .HasColumnType("integer")
                        .HasColumnName("contract_matches");

                    b.Property<int>("MatchesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("matches_played");

                    b.Property<decimal>("PerMatchFee")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("per_match_fee");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("season_id");

                    b.Property<DateTimeOffset>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<Guid>("SponsorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sponsor_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_sponsor_contracts");

                    b.HasIndex("SponsorId")
                        .HasDatabaseName("ix_sponsor_contracts_sponsor_id");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("ix_sponsor_contracts_team_id");

                    b.HasIndex("TeamId", "Status")
                        .HasDatabaseName("ix_sponsor_contracts_team_id_status");

                    b.ToTable("sponsor_contracts", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Teams.Stadium", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5000)
                        .HasColumnName("capacity");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("club_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal>("TicketPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(10m)
                        .HasColumnName("ticket_price");

                    b.HasKey("Id")
                        .HasName("pk_stadiums");

                    b.HasIndex("ClubId")
                        .IsUnique()
                        .HasDatabaseName("ix_stadiums_club_id");

                    b.ToTable("stadiums", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActiveSponsorContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_sponsor_contract_id");

                    b.Property<bool>("IsManagerClub")
                        .HasColumnType("boolean")
                        .HasColumnName("is_manager_club");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("primary_color");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("secondary_color");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("short_name");

                    b.Property<Guid?>("StadiumId")
                        .HasColumnType("uuid")
                        .HasColumnName("stadium_id");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("ActiveSponsorContractId")
                        .HasDatabaseName("ix_teams_active_sponsor_contract_id");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_teams_name");

                    b.HasIndex("StadiumId")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_stadium_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Teams.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ContractSeasons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(3)
                        .HasColumnName("contract_seasons");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<int>("StartSeasonNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("start_season_number");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_team_memberships");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_team_memberships_player_id");

                    b.HasIndex("TeamId", "StartDate")
                        .HasDatabaseName("ix_team_memberships_team_id_start_date");

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Transfers.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int?>("ArrivalRoundNumber")
                        .HasColumnType("integer")
                        .HasColumnName("arrival_round_id");

                    b.Property<Guid?>("ArrivalSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("arrival_season_id");

                    b.Property<int>("ArrivalSeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("arrival_season_number");

                    b.Property<Guid>("BuyingClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("buying_club_id");

                    b.Property<DateOnly?>("CompletedAt")
                        .HasColumnType("date")
                        .HasColumnName("completed_at");

                    b.Property<decimal>("Fee")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("fee");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("ProposalSeasonId")
                        .HasColumnType("uuid")
                        .HasColumnName("proposal_season_id");

                    b.Property<DateOnly>("ProposedAt")
                        .HasPrecision(14, 2)
                        .HasColumnType("date")
                        .HasColumnName("proposed_at");

                    b.Property<DateOnly?>("ResolvedAt")
                        .HasColumnType("date")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("SellingClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("selling_club_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_transfers");

                    b.HasIndex("ArrivalSeasonId")
                        .HasDatabaseName("ix_transfers_arrival_season_id");

                    b.HasIndex("BuyingClubId")
                        .HasDatabaseName("ix_transfers_buying_club_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_transfers_player_id");

                    b.HasIndex("ArrivalSeasonNumber", "Status")
                        .HasDatabaseName("ix_transfers_arrival_season_number_status");

                    b.HasIndex("ProposalSeasonId", "Status")
                        .HasDatabaseName("ix_transfers_proposal_season_id_status");

                    b.HasIndex("SellingClubId", "BuyingClubId", "PlayerId")
                        .HasDatabaseName("ix_transfers_selling_club_id_buying_club_id_player_id");

                    b.ToTable("transfers", (string)null);
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.CompetitionParticipant", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Competitions.CompetitionSeason", null)
                        .WithMany()
                        .HasForeignKey("CompetitionSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competition_participants_competition_seasons_competition_se");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_participants_teams_team_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.CompetitionSeason", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Competitions.Competition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_seasons_competitions_competition_id");

                    b.HasOne("NinjaEleven.Domain.Seasons.Division", null)
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_competition_seasons_divisions_division_id");

                    b.HasOne("NinjaEleven.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_competition_seasons_seasons_season_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.CupTie", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cup_ties_teams_away_team_id");

                    b.HasOne("NinjaEleven.Domain.Competitions.CompetitionSeason", null)
                        .WithMany()
                        .HasForeignKey("CompetitionSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cup_ties_competition_seasons_competition_season_id");

                    b.HasOne("NinjaEleven.Domain.Matches.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FirstLegFixtureId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cup_ties_fixtures_first_leg_fixture_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cup_ties_teams_home_team_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("LoserTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cup_ties_teams_loser_team_id");

                    b.HasOne("NinjaEleven.Domain.Matches.Fixture", null)
                        .WithMany()
                        .HasForeignKey("SecondLegFixtureId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cup_ties_fixtures_second_leg_fixture_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("WinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cup_ties_teams_winner_team_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.MatchDay", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_days_seasons_season_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.Round", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Competitions.CompetitionSeason", null)
                        .WithMany()
                        .HasForeignKey("CompetitionSeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rounds_competition_seasons_competition_season_id");

                    b.HasOne("NinjaEleven.Domain.Competitions.MatchDay", null)
                        .WithMany()
                        .HasForeignKey("MatchDayId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_rounds_match_days_match_day_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Competitions.TrophyAward", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Competitions.CompetitionSeason", null)
                        .WithMany()
                        .HasForeignKey("CompetitionSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trophy_awards_competition_seasons_competition_season_id");

                    b.HasOne("NinjaEleven.Domain.Seasons.Division", null)
                        .WithMany()
                        .HasForeignKey("DivisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_trophy_awards_divisions_division_id");

                    b.HasOne("NinjaEleven.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trophy_awards_seasons_season_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_trophy_awards_teams_team_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Finance.FinanceMovement", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_finance_movements_matches_match_id");

                    b.HasOne("NinjaEleven.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_finance_movements_seasons_season_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_finance_movements_teams_team_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.Fixture", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_teams_away_team_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_teams_home_team_id");

                    b.HasOne("NinjaEleven.Domain.Competitions.Round", null)
                        .WithMany()
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fixtures_rounds_round_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.Match", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_teams_away_team_id");

                    b.HasOne("NinjaEleven.Domain.Matches.Fixture", null)
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matches_fixtures_fixture_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_matches_teams_home_team_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.MatchEvent", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_events_matches_match_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.MatchPlayerStatistics", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Matches.Match", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_player_statistics_matches_match_id");

                    b.HasOne("NinjaEleven.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_player_statistics_players_player_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Matches.MatchStatistics", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Matches.Match", null)
                        .WithOne()
                        .HasForeignKey("NinjaEleven.Domain.Matches.MatchStatistics", "MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_match_statistics_matches_match_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Players.PlayerSeasonState", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_states_players_player_id");

                    b.HasOne("NinjaEleven.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_player_season_states_seasons_season_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_player_season_states_teams_team_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Sponsors.SponsorContract", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Sponsors.Sponsor", "Sponsor")
                        .WithMany()
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sponsor_contracts_sponsors_sponsor_id");

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Teams.Team", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Sponsors.SponsorContract", "ActiveSponsorContract")
                        .WithMany()
                        .HasForeignKey("ActiveSponsorContractId")
                        .HasConstraintName("fk_teams_sponsor_contracts_active_sponsor_contract_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Stadium", "Stadium")
                        .WithOne()
                        .HasForeignKey("NinjaEleven.Domain.Teams.Team", "StadiumId")
                        .HasConstraintName("fk_teams_stadiums_stadium_id");

                    b.Navigation("ActiveSponsorContract");

                    b.Navigation("Stadium");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Teams.TeamMembership", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_players_player_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_memberships_teams_team_id");
                });

            modelBuilder.Entity("NinjaEleven.Domain.Transfers.Transfer", b =>
                {
                    b.HasOne("NinjaEleven.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("ArrivalSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transfers_seasons_arrival_season_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("BuyingClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfers_teams_buying_club_id");

                    b.HasOne("NinjaEleven.Domain.Players.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfers_players_player_id");

                    b.HasOne("NinjaEleven.Domain.Seasons.Season", null)
                        .WithMany()
                        .HasForeignKey("ProposalSeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_transfers_seasons_proposal_season_id");

                    b.HasOne("NinjaEleven.Domain.Teams.Team", null)
                        .WithMany()
                        .HasForeignKey("SellingClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transfers_teams_selling_club_id");
                });
#pragma warning restore 612, 618
        }
    }
}
